name: torchsml
channels:
  - anaconda
  - conda-forge
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - cerberus=1.3.5
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.10.15
  - debugpy=1.8.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.16.1
  - freetype=2.12.1
  - fsspec=2024.10.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.2
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libtiff=4.7.0
  - libtorch=2.4.1
  - libuv=1.49.2
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lightning-utilities=0.11.8
  - llvm-openmp=19.1.2
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.15
  - python-dateutil=2.9.0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.4.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - rich=13.9.4
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - setuptools=75.1.0
  - six=1.16.0
  - sleef=3.7
  - stack_data=0.6.2
  - sympy=1.13.3
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - torchmetrics=1.5.1
  - torchvision=0.19.1
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zstd=1.5.6