model:
  name: CustomModel
  params:
    input_size: 784
    output_size: 10

dataset:
  name: CustomDataset
  params:
    input_size: 784
    output_size: 10

loss:
  name: CustomLoss
  params: {}

optimizer:
  name: CustomOptimizer
  params:
    learning_rate: 0.001

callbacks:
  - name: CustomCallback
    params: {}

training:
  num_epochs: 10
  batch_size: 64